Adds support for Chevrolet Bolt EV, Bolt EUV
Ben-Chapman/EVFinder pull request #55
Opened 2022-11-05 10:14 UTC by blamejoel

This change resolves #42 with a starting point for Chevrolet EV support.

2022-11-05 12:43 UTC, Ben-Chapman commented
Amazing! Thanks for taking the time to put this together, I'll take a look at the PR this weekend.

2022-11-06 16:00 UTC, Ben-Chapman requested changes
This looks really good, thanks for sending it in.

Just a few minor changes needed, see inline comments. Can you also pull in the `dealerUrl` changes detailed in https://github.com/Ben-Chapman/EVFinder/issues/56

2022-11-08 05:55 UTC, blamejoel commented on api/src/blueprints/chevrolet.py
> +      verify=False
Just an artifact from using volkswagen.py as a starting point reference. Removed!

2022-11-08 06:02 UTC, blamejoel commented on app/src/manufacturers/chevroletMappings.js
> +  'vehicleAvailabilityDisplayStatus': 'inventoryStatus',
Whoops, artifact from using genesisMappings.js as a starting reference. Fixed.

2022-11-08 06:54 UTC, blamejoel commented on api/src/blueprints/chevrolet.py
> +      'model': request.args.get('model'),
Hm. Accessing the request.args this way (`.get(<arg>)`) should follow the [application/x-www-form-urlencoded spec](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1) and auto decode the `+` into a space automatically. Are you seeing an issue on a deployed staging instance? It's decoding correctly on my local dev venv, but if it's not working on the deployed I'd also be curious as to what other nuances may show up elsewhere.

2022-11-08 06:56 UTC, blamejoel commented on api/src/blueprints/chevrolet.py
> +def get_chevrolet_inventory():
Yikes, that spacing was all over the place; good catch, thanks!

2022-11-08 07:32 UTC, blamejoel commented
I looked around at the Chevrolet API and there's an endpoint for getting dealer info including dealer URLs, but you have to query it for each dealer--which could potentially turn into a lot of additional network requests on each search.

Since it's unlikely the URL for any given dealer will change all that frequently, we could cache the dealer <-> URL mapping on localStorage/vue store or another more persistent option (db). Regardless of strategy, an API call (local or external) will be needed for each new dealer in the `Set` of dealers from all returned results to allow the dealer name to be hyperlinked for Chevrolet.

Alternatively, we could make the dealer name clickable and just use a clickhandler for Chevrolet specifically that gets the URL from the API at runtime (on click) and navigates to it; the tradeoff here would be having to wait on the synchronous API call to fetch the dealer URL, _and then_ loading the URL in the new page. It's also worth noting that some browsers may not let the JavaScript "build" the URL to open in a new window like this so we'd have do a workaround by opening the new window, making the fetch request to load the resource, then writing the data to the new window.

2022-11-08 13:50 UTC, Ben-Chapman commented on api/src/blueprints/chevrolet.py
> +      'model': request.args.get('model'),
Huh, interesting, it is something with my local environment. I deployed this out to dev (dev.theevfinder.com) and it's working as expected - so ... nevermind :)

2022-11-08 16:10 UTC, Ben-Chapman commented
It's interesting that the Chevrolet API does not return _any_ information for a dealer, unless you dill down into the detail for a specific vehicle. I like the ClickHandler idea, but in looking at the stats few people (<5%) click on the dealer link so I think it's fine as is.

I just pushed the hero imagery into your fork, and from what I can see this is good to ship.

2022-11-08 16:31 UTC, merged